services:
  campaigns:
    build:
      context: .
      dockerfile: ./apps/campaigns/Dockerfile
      target: development
    command: pnpm run start:dev campaigns
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
